import ReactECharts from 'echarts-for-react'
import { memo } from 'react'
import { useCashflowAnalytics, useCashflowStore } from '../../../store/cashflowStore'
import { useTheme } from '../../themes/ThemeProvider'
import { PanelCard } from '../../shared/components/PanelCard'
import { StatsBadge } from '../../shared/components/StatsBadge'
export const CashflowSummaryTile = memo(function CashflowSummaryTile() { const a = useCashflowAnalytics(); return <PanelCard title="Cashflow Summary" subtitle="Gross, discounted, realized, and future cashflows" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3 sm:grid-cols-3"><StatsBadge label="Gross CF" value={a.grossCashflow.toFixed(2)} /><StatsBadge label="PV" value={a.presentValue.toFixed(2)} tone="primary" /><StatsBadge label="Paid" value={a.realized.toFixed(2)} tone="success" /><StatsBadge label="Remaining" value={a.future.toFixed(2)} /><StatsBadge label="Total P&L" value={a.totalPnL.toFixed(2)} tone={a.totalPnL >= 0 ? 'success' : 'danger'} /></div></PanelCard> })
export const CashflowTimelineTile = memo(function CashflowTimelineTile() { const { tokens } = useTheme(); const a = useCashflowAnalytics(); const select = useCashflowStore((s) => s.selectCashflow); return <PanelCard title="Cashflow Timeline" subtitle="Settlement cashflows through time" className="h-full"><ReactECharts option={{ grid: { left: 42, right: 20, top: 24, bottom: 42 }, tooltip: { trigger: 'axis' }, xAxis: { type: 'category', data: a.cashflows.map((c: import('../../../store/cashflowStore').Cashflow) => c.date.slice(0, 7)), axisLabel: { color: tokens.muted, fontSize: 9, interval: 5 } }, yAxis: { type: 'value', axisLabel: { color: tokens.muted, fontSize: 9 }, splitLine: { lineStyle: { color: tokens.grid } } }, series: [{ type: 'bar', data: a.cashflows.map((c: import('../../../store/cashflowStore').Cashflow) => ({ value: c.amount, itemStyle: { color: c.type === 'coupon' ? tokens.primary : tokens.success } })) }] }} style={{ height: '100%', width: '100%' }} notMerge onEvents={{ click: (p: { dataIndex?: number }) => typeof p.dataIndex === 'number' && select(a.cashflows[p.dataIndex]!.id) }} /></PanelCard> })
export const CashflowDetailTile = memo(function CashflowDetailTile() { const a = useCashflowAnalytics(); const selected = useCashflowStore((s) => s.selectedCashflowId) ?? a.cashflows[0]!.id; const c = a.cashflows.find((x: import('../../../store/cashflowStore').Cashflow) => x.id === selected) ?? a.cashflows[0]!; return <PanelCard title="Cashflow Detail Explorer" subtitle="Lineage from event to discounted cashflow" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3"><StatsBadge label="Type" value={c.type} /><StatsBadge label="Date" value={c.date} /><StatsBadge label="Amount" value={c.amount.toFixed(2)} tone={c.amount >= 0 ? 'success' : 'danger'} /><StatsBadge label="Probability" value={`${(c.probability * 100).toFixed(1)}%`} /><StatsBadge label="Discount Factor" value={c.discountFactor.toFixed(4)} /><StatsBadge label="Present Value" value={c.presentValue.toFixed(2)} tone="primary" /></div></PanelCard> })
export const PnLSummaryTile = memo(function PnLSummaryTile() { const a = useCashflowAnalytics(); return <PanelCard title="P&L Summary" subtitle="Realized, unrealized, carry, and mark-to-market" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3"><StatsBadge label="Realized P&L" value={a.realizedPnL.toFixed(2)} tone="success" /><StatsBadge label="Unrealized P&L" value={a.unrealizedPnL.toFixed(2)} tone="primary" /><StatsBadge label="MTM P&L" value={a.mtmPnL.toFixed(2)} /><StatsBadge label="Carry P&L" value={a.carryPnL.toFixed(2)} tone="warning" /><StatsBadge label="Total P&L" value={a.totalPnL.toFixed(2)} tone={a.totalPnL >= 0 ? 'success' : 'danger'} /></div></PanelCard> })
export const PnLTimelineTile = memo(function PnLTimelineTile() { const { tokens } = useTheme(); const a = useCashflowAnalytics(); let cumulative = 0; const values = a.cashflows.map((c: import('../../../store/cashflowStore').Cashflow) => { cumulative += c.presentValue - (c.realized ? c.amount : 0); return +cumulative.toFixed(2) }); return <PanelCard title="P&L Timeline" subtitle="Mark-to-market evolution and cumulative contribution" className="h-full"><ReactECharts option={{ grid: { left: 42, right: 20, top: 24, bottom: 42 }, legend: { top: 2, textStyle: { color: tokens.muted, fontSize: 9 } }, xAxis: { type: 'category', data: a.cashflows.map((c: import('../../../store/cashflowStore').Cashflow) => c.date.slice(0, 7)), axisLabel: { color: tokens.muted, fontSize: 9, interval: 5 } }, yAxis: { type: 'value', axisLabel: { color: tokens.muted, fontSize: 9 }, splitLine: { lineStyle: { color: tokens.grid } } }, series: [{ name: 'Cumulative P&L', type: 'line', data: values, smooth: true, lineStyle: { color: tokens.primary, width: 2 }, areaStyle: { opacity: .12, color: tokens.primary } }] }} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })
