import ReactECharts from 'echarts-for-react'
import { memo, useEffect, useState } from 'react'
import { useExplorerStore, useSelectedPath } from '../../../store/explorerStore'
import { executionEvents } from '../../payoff-graph/data/executionContexts'
import { useTheme } from '../../themes/ThemeProvider'
import { PanelCard } from '../../shared/components/PanelCard'
import { StatsBadge } from '../../shared/components/StatsBadge'
const colors: Record<string, string> = { 'Coupon Observation': '#f59e0b', 'KO Observation': '#22c55e', 'Barrier Observation': '#3b82f6', 'Final Fixing': '#a855f7', Settlement: '#ef4444' }
export const ScheduleExplorerTile = memo(function ScheduleExplorerTile() { const path = useSelectedPath(); const setDate = useExplorerStore((s) => s.setSelectedDateIndex); const selected = useExplorerStore((s) => s.selectedDateIndex); const events = executionEvents(path); const [playing, setPlaying] = useState(false); useEffect(() => { if (!playing) return; const id = window.setInterval(() => setDate((selected + 1) % events.length), 700); return () => window.clearInterval(id) }, [playing, selected, events.length, setDate]); const jump = (i: number) => setDate(Math.max(0, Math.min(events.length - 1, i))); return <PanelCard title="Schedule Explorer" subtitle="Generated observation and settlement calendar" className="h-full"><div className="flex h-full flex-col p-3"><div className="flex justify-between text-[10px] text-muted"><span>Issue · {events[0]!.date}</span><span>Final Fixing · {events.at(-1)!.date}</span></div><div className="relative mt-8 flex items-center">{events.map((e, i) => <button key={e.date} type="button" title={`${e.date} · ${e.type}`} onClick={() => jump(i)} className="group relative flex-1"><span className="absolute left-0 right-0 top-1/2 h-px bg-line" /><span className="relative z-10 mx-auto block h-3 w-3 rounded-full border-2" style={{ background: i === selected ? colors[e.type] : 'var(--theme-panel)', borderColor: colors[e.type] }} /></button>)}</div><div className="mt-6 flex justify-center gap-1"><button className="shock-button" onClick={() => jump(0)} type="button">|◀</button><button className="shock-button" onClick={() => jump(selected - 1)} type="button">◀</button><button className="shock-button" onClick={() => setPlaying(!playing)} type="button">{playing ? 'Pause' : 'Play'}</button><button className="shock-button" onClick={() => jump(selected + 1)} type="button">▶</button><button className="shock-button" onClick={() => jump(events.length - 1)} type="button">▶|</button></div><p className="mt-4 text-center text-xs font-semibold text-main">{events[selected]!.date} · {events[selected]!.type}</p></div></PanelCard> })
export const ObservationExplorerTile = memo(function ObservationExplorerTile() { const path = useSelectedPath(); const i = useExplorerStore((s) => s.selectedDateIndex); const e = executionEvents(path)[i]!; return <PanelCard title="Observation Explorer" subtitle="Observation output bridged into payoff evaluation" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3"><StatsBadge label="Observation Date" value={e.date} /><StatsBadge label="Worst Of" value={`${e.worstOf}%`} tone={e.worstOf < 70 ? 'danger' : 'primary'} /><StatsBadge label="Coupon Range" value={e.coupon ? 'TRUE' : 'FALSE'} tone={e.coupon ? 'success' : 'warning'} /><StatsBadge label="KI Status" value={e.ki ? 'TRUE' : 'FALSE'} tone={e.ki ? 'danger' : undefined} /><StatsBadge label="KO Status" value={e.ko ? 'TRUE' : 'FALSE'} tone={e.ko ? 'success' : undefined} /><StatsBadge label="Event Type" value={e.type} /></div></PanelCard> })
export const ExecutionStateInspectorTile = memo(function ExecutionStateInspectorTile() { const path = useSelectedPath(); const i = useExplorerStore((s) => s.selectedDateIndex); const e = executionEvents(path)[i]!; return <PanelCard title="Execution State Inspector" subtitle="Runtime state at selected event" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3"><StatsBadge label="Date" value={e.date} /><StatsBadge label="Worst Of" value={`${e.worstOf}%`} /><StatsBadge label="Coupon Memory" value={e.coupon ? 'Accruing' : 'No hit'} /><StatsBadge label="Settlement" value={e.type === 'Final Fixing' ? 'Pending' : 'Not generated'} /><StatsBadge label="Payoff Estimate" value={path.attribution.totalPv.toFixed(2)} tone="primary" /></div></PanelCard> })
export const LifecycleOverviewTile = memo(function LifecycleOverviewTile() { const { tokens } = useTheme(); return <PanelCard title="Lifecycle Overview" subtitle="Event-driven product execution layers" className="h-full"><ReactECharts option={{ series: [{ type: 'funnel', left: '12%', top: 10, bottom: 10, width: '76%', min: 0, max: 100, sort: 'none', label: { color: tokens.text, fontSize: 10 }, data: ['Issue', 'Observation Phase', 'Coupon Phase', 'KO Phase', 'Final Fixing', 'Settlement'].map((name, i) => ({ name, value: 100 - i * 12, itemStyle: { color: [tokens.primary, tokens.chartMuted, tokens.warning, tokens.success, '#a855f7', tokens.danger][i] } })) }] }} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })
