import { memo } from 'react'
import { useExplainLedger } from '../../../hooks'
import { useExplainLedgerStore, type ExplainSource } from '../../../store/explainLedgerStore'
import { PanelCard } from '../../shared/components/PanelCard'
import { PanelLoading } from '../../shared/components/AsyncPanel'
import { StatsBadge } from '../../shared/components/StatsBadge'
const sources: ExplainSource[] = ['market', 'plva', 'cashflow', 'valuation', 'risk']
export const ExplainLedgerTableTile = memo(function ExplainLedgerTableTile() { const { data } = useExplainLedger(); const select = useExplainLedgerStore((s) => s.selectEntry); const source = useExplainLedgerStore((s) => s.selectedSource); const selectSource = useExplainLedgerStore((s) => s.selectSource); const entries = data?.entries.filter((e) => !source || e.source === source) ?? []; if (!data) return <PanelLoading title="Explain Ledger Table" subtitle="Canonical explain entries — one source of truth for all views" />; return <PanelCard title="Explain Ledger Table" subtitle="Canonical explain entries — one source of truth for all views" className="h-full"><div className="flex h-full min-h-0 flex-col p-2"><div className="mb-2 flex gap-1"><button className="shock-button" onClick={() => selectSource(undefined)} type="button">All</button>{sources.map((s) => <button className="shock-button" key={s} onClick={() => selectSource(source === s ? undefined : s)} type="button">{s}</button>)}</div><div className="min-h-0 flex-1 overflow-auto"><table className="w-full text-left text-[10px]"><thead className="sticky top-0 bg-panel text-muted"><tr><th className="p-2">Date</th><th className="p-2">Source</th><th className="p-2">Category</th><th className="p-2">Subcategory</th><th className="p-2 text-right">Contribution</th></tr></thead><tbody>{entries.map((e) => <tr key={e.id} onClick={() => select(e.id)} className="cursor-pointer border-t border-line hover:bg-surface"><td className="p-2 text-muted">{e.timestamp}</td><td className="p-2 font-semibold uppercase">{e.source}</td><td className="p-2 text-main">{e.category}</td><td className="p-2 text-muted">{e.subCategory ?? '—'}</td><td className={`p-2 text-right font-mono ${e.contribution >= 0 ? 'text-success' : 'text-danger'}`}>{e.contribution >= 0 ? '+' : ''}{e.contribution.toFixed(2)}</td></tr>)}</tbody></table></div></div></PanelCard> })
export const ExplainLedgerExplorerTile = memo(function ExplainLedgerExplorerTile() { const { data } = useExplainLedger(); const selectedId = useExplainLedgerStore((s) => s.selectedEntryId); const e = data?.entries.find((x) => x.id === selectedId) ?? data?.entries[0]; if (!data || !e) return <PanelLoading title="Explain Ledger Explorer" subtitle="Selected entry and lineage metadata" />; return <PanelCard title="Explain Ledger Explorer" subtitle="Selected entry and lineage metadata" className="h-full"><div className="space-y-2 p-3"><div className="rounded-lg border border-line bg-surface p-3"><p className="eyebrow">{e.source} · {e.category}</p><p className="mt-1 text-sm font-semibold text-main">{e.description}</p><p className="mt-2 text-xs text-muted">Every waterfall, tree, timeline, and reconciliation view reads this contribution from the ledger.</p></div><div className="grid grid-cols-2 gap-2"><StatsBadge label="Subcategory" value={e.subCategory ?? '—'} /><StatsBadge label="Currency" value={e.currency} /><StatsBadge label="Contribution" value={e.contribution.toFixed(2)} tone={e.contribution >= 0 ? 'success' : 'danger'} /><StatsBadge label="Timestamp" value={e.timestamp} /></div></div></PanelCard> })
export const ExplainReconciliationTile = memo(function ExplainReconciliationTile() { const { data } = useExplainLedger(); if (!data) return <PanelLoading title="Explain Reconciliation" subtitle="Explained contributions versus actual P&L" />; const r = data.reconciliation; return <PanelCard title="Explain Reconciliation" subtitle="Explained contributions versus actual P&L" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3"><StatsBadge label="Market" value={r.totalMarket.toFixed(2)} tone="primary" /><StatsBadge label="PLVA" value={r.totalPLVA.toFixed(2)} tone="warning" /><StatsBadge label="Cashflow" value={r.totalCashflow.toFixed(2)} tone="success" /><StatsBadge label="Valuation" value={r.totalValuation.toFixed(2)} /><StatsBadge label="Explained" value={r.explained.toFixed(2)} /><StatsBadge label="Residual" value={r.residual.toFixed(2)} tone={Math.abs(r.residual) < .2 ? 'success' : 'danger'} /></div></PanelCard> })