import ReactECharts from 'echarts-for-react'
import { memo, useMemo } from 'react'
import { finalMC, MC_PATH_COUNTS, mcDiagnostics, mcEfficiency } from '../../../mock-data/mcDiagnostics'
import { useTheme } from '../../themes/ThemeProvider'
import { PanelCard } from '../../shared/components/PanelCard'
import { StatsBadge } from '../../shared/components/StatsBadge'

const useChart = () => { const { tokens } = useTheme(); return { tokens, base: { backgroundColor: 'transparent', textStyle: { color: tokens.text }, tooltip: { trigger: 'axis', backgroundColor: tokens.panel, borderColor: tokens.border, textStyle: { color: tokens.text, fontSize: 11 } }, grid: { left: 48, right: 22, top: 38, bottom: 40 }, xAxis: { type: 'log', logBase: 10, axisLabel: { color: tokens.muted, fontSize: 9 }, axisLine: { lineStyle: { color: tokens.border } } }, yAxis: { type: 'value', axisLabel: { color: tokens.muted, fontSize: 9 }, splitLine: { lineStyle: { color: tokens.grid } } } } } }
const x = MC_PATH_COUNTS
const line = (name: string, values: number[], color: string, width = 2) => ({ name, type: 'line', data: x.map((paths, i) => [paths, values[i]]), symbol: 'circle', symbolSize: 4, lineStyle: { color, width }, itemStyle: { color } })

export const SimulationSummaryTile = memo(function SimulationSummaryTile() { return <PanelCard title="Simulation Summary" subtitle="Executive simulation health at 1,000,000 paths" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3 sm:grid-cols-4"><StatsBadge label="Path Count" value={finalMC.paths.toLocaleString()} tone="primary" /><StatsBadge label="PV Estimate" value={finalMC.pv} tone="success" /><StatsBadge label="MC Std Error" value={finalMC.se} tone="warning" /><StatsBadge label="95% CI" value={`${finalMC.lower} – ${finalMC.upper}`} /><StatsBadge label="KI Probability" value={`${finalMC.ki}%`} /><StatsBadge label="KO Probability" value={`${finalMC.ko}%`} /><StatsBadge label="Convergence" value="YES" tone="success" /><StatsBadge label="Confidence" value="HIGH" tone="success" /></div></PanelCard> })

export const PVConvergenceTile = memo(function PVConvergenceTile() { const { base, tokens } = useChart(); const option = useMemo(() => ({ ...base, legend: { top: 4, textStyle: { color: tokens.muted, fontSize: 9 }, data: ['PV Estimate', '95% Confidence Band', 'Final PV'] }, xAxis: { ...base.xAxis, name: 'Path Count (log)' }, yAxis: { ...base.yAxis, name: 'PV Estimate' }, series: [{ ...line('95% Confidence Band', mcDiagnostics.map((d) => d.upper), tokens.primary), data: mcDiagnostics.map((d) => [d.paths, d.upper]), lineStyle: { opacity: 0 }, areaStyle: { opacity: .16, color: tokens.primary }, symbol: 'none' }, { ...line('PV Estimate', mcDiagnostics.map((d) => d.pv), tokens.primary, 3) }, { name: 'Final PV', type: 'line', data: [[x[0], finalMC.pv], [x[x.length - 1], finalMC.pv]], symbol: 'none', lineStyle: { color: tokens.text, type: 'dashed' } }] }), [base, tokens]); return <PanelCard title="PV Convergence" subtitle="Running estimate, confidence band, and final estimate" className="h-full"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })

export const ConfidenceIntervalShrinkageTile = memo(function ConfidenceIntervalShrinkageTile() { const { base, tokens } = useChart(); const option = { ...base, xAxis: { ...base.xAxis, name: 'Path Count (log)' }, yAxis: { ...base.yAxis, name: '95% CI Width' }, series: [line('CI Width', mcDiagnostics.map((d) => +(d.upper - d.lower).toFixed(2)), tokens.warning, 3)] }; return <PanelCard title="Confidence Interval Shrinkage" subtitle="Uncertainty reduction as paths increase" className="h-full"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })

export const ErrorVsPathCountTile = memo(function ErrorVsPathCountTile() { const { base, tokens } = useChart(); const theoretical = x.map((n) => +(0.22 * Math.sqrt(100000 / n)).toFixed(3)); const option = { ...base, xAxis: { ...base.xAxis, name: 'Path Count (log-log)' }, yAxis: { ...base.yAxis, name: 'Error', type: 'log' }, legend: { top: 4, textStyle: { color: tokens.muted, fontSize: 9 } }, series: [line('Observed Error', mcDiagnostics.map((d) => d.se), tokens.primary, 3), line('Theoretical 1/√N', theoretical, tokens.warning)] }; return <PanelCard title="Error vs Path Count" subtitle="Observed error against theoretical 1/√N decay" className="h-full"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })

function ProbabilityTile({ kind }: { kind: 'KI' | 'KO' }) { const { base, tokens } = useChart(); const values = mcDiagnostics.map((d) => kind === 'KI' ? d.ki : d.ko); const color = kind === 'KI' ? tokens.danger : tokens.success; const option = { ...base, xAxis: { ...base.xAxis, name: 'Path Count (log)' }, yAxis: { ...base.yAxis, name: 'Probability %', max: kind === 'KI' ? 30 : 75, min: kind === 'KI' ? 18 : 55 }, series: [line(`${kind} Probability`, values, color, 3)] }; return <PanelCard title={`${kind} Probability Convergence`} subtitle={`${kind} probability stability`} className="h-full"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> }
export const KIProbabilityConvergenceTile = memo(() => <ProbabilityTile kind="KI" />)
export const KOProbabilityConvergenceTile = memo(() => <ProbabilityTile kind="KO" />)

export const PercentileConvergenceTile = memo(function PercentileConvergenceTile() { const { base, tokens } = useChart(); const option = { ...base, xAxis: { ...base.xAxis, name: 'Path Count (log)' }, yAxis: { ...base.yAxis, name: 'Terminal Payoff' }, legend: { top: 4, textStyle: { color: tokens.muted, fontSize: 9 } }, series: [line('P05', mcDiagnostics.map((d) => d.p05), tokens.danger), line('P50', mcDiagnostics.map((d) => d.p50), tokens.primary, 3), line('P95', mcDiagnostics.map((d) => d.p95), tokens.success)] }; return <PanelCard title="Percentile Convergence" subtitle="Central estimate versus moving tails" className="h-full"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })

export const DistributionStabilityTile = memo(function DistributionStabilityTile() { const { base, tokens } = useChart(); const series = [10000, 50000, 100000, 500000].map((n, j) => ({ name: `${n / 1000}k Paths`, type: 'line', symbol: 'none', lineStyle: { color: [tokens.warning, tokens.primary, tokens.success, tokens.text][j], opacity: .85 }, data: mcDiagnostics.map((d, i) => [d.p50 + (i < 4 ? (3 - i) * (j % 2 ? .4 : -.3) : 0), Math.exp(-((d.p50 - 96) ** 2) / (20 + j * 5))]) })); return <PanelCard title="Distribution Stability" subtitle="Terminal payoff distribution overlap" className="h-full"><ReactECharts option={{ ...base, xAxis: { ...base.xAxis, type: 'value', name: 'Terminal Payoff' }, yAxis: { ...base.yAxis, name: 'Relative density' }, legend: { top: 4, textStyle: { color: tokens.muted, fontSize: 9 } }, series }} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })

export const SimulationEfficiencyTile = memo(function SimulationEfficiencyTile() { const { base, tokens } = useChart(); return <PanelCard title="Simulation Efficiency" subtitle="Paths required to reach target error" className="h-full"><ReactECharts option={{ ...base, grid: { left: 100, right: 24, top: 24, bottom: 30 }, xAxis: { ...base.xAxis, type: 'value', name: 'Paths' }, yAxis: { type: 'category', data: mcEfficiency.map((d) => d.name), axisLabel: { color: tokens.muted, fontSize: 9 } }, series: [{ type: 'bar', data: mcEfficiency.map((d) => d.paths), itemStyle: { color: tokens.primary }, label: { show: true, position: 'right', color: tokens.text, formatter: ({ value }: { value: number }) => value.toLocaleString() } }] }} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })

export const ConvergenceHealthTile = memo(function ConvergenceHealthTile() { return <PanelCard title="Convergence Health" subtitle="Assessment from current error, CI width, and PV drift" className="h-full"><div className="flex h-full flex-col justify-center gap-3 p-4"><div className="flex items-center gap-3"><span className="h-5 w-5 rounded-full bg-success shadow-[0_0_18px_var(--theme-success)]" /><div><p className="text-lg font-semibold text-success">GREEN · CONVERGED</p><p className="text-xs text-muted">Current simulation result is stable enough for review.</p></div></div><div className="grid grid-cols-3 gap-2"><StatsBadge label="PV Drift" value="0.03" /><StatsBadge label="CI Width" value={`${(finalMC.upper - finalMC.lower).toFixed(2)}`} /><StatsBadge label="Error" value={finalMC.se} tone="success" /></div></div></PanelCard> })
