import ReactECharts from 'echarts-for-react'
import { memo, useMemo } from 'react'
import { useSelectedPath } from '../../../store/explorerStore'
import { useSimulationStore } from '../../../store/simulationStore'
import { useTradeEconomicsStore } from '../../../store/tradeEconomicsStore'
import { PanelLoading } from '../../shared/components/AsyncPanel'
import { useTheme } from '../../themes/ThemeProvider'

function baseOption(colors: ReturnType<typeof useTheme>['tokens']) {
  return { backgroundColor: 'transparent', animationDuration: 250, textStyle: { color: colors.text }, tooltip: { trigger: 'axis', axisPointer: { type: 'cross' }, backgroundColor: colors.panel, borderColor: colors.border, textStyle: { color: colors.text, fontSize: 11 } }, grid: { left: 46, right: 24, top: 56, bottom: 34 }, xAxis: { type: 'category', axisLabel: { color: colors.muted, fontSize: 9 }, axisLine: { lineStyle: { color: colors.border } } }, yAxis: { type: 'value', axisLabel: { color: colors.muted, fontSize: 9 }, splitLine: { lineStyle: { color: colors.grid } } } }
}

function percentile(value: number, values: number[]) { return Math.round(values.filter((v) => v <= value).length / values.length * 100) }

export const QuantileFanTile = memo(function QuantileFanTile() {
  const path = useSelectedPath(); const economics = useTradeEconomicsStore(); const { tokens, mode } = useTheme()
  const bundle = useSimulationStore((s) => s.bundle)
  const paths = bundle?.paths ?? []
  const dates = paths[0]?.dates ?? []
  const terminalValues = paths.map((p) => p.worstOfPerformance[p.worstOfPerformance.length - 1]!)
  const terminalPercentile = path ? percentile(path.worstOfPerformance[path.worstOfPerformance.length - 1]!, terminalValues) : 0
  const currentPercentile = path ? percentile(path.worstOfPerformance[0]!, paths.map((p) => p.worstOfPerformance[0]!)) : 0
  const pathIndex = path?.pathIndex ?? 0
  const selectedSeries = path ? path.worstOfPerformance.map((v) => +(v * 100).toFixed(1)) : []
  const option = useMemo(() => {
    const quantiles = [5, 10, 25, 50, 75, 90, 95].map((q) => dates.map((_, i) => { const values = paths.map((p) => p.worstOfPerformance[i]!).sort((a, b) => a - b); return +(values[Math.floor((q / 100) * (values.length - 1))]! * 100).toFixed(1) }))
    const [p05, p10, p25, p50, p75, p90, p95] = quantiles
    const band = (name: string, lower: number[], upper: number[], opacity: number) => [{ name, type: 'line', data: lower, stack: name, symbol: 'none', lineStyle: { opacity: 0 }, areaStyle: { opacity: 0 }, tooltip: { show: false } }, { name, type: 'line', data: upper.map((value, i) => +(value - lower[i]!).toFixed(1)), stack: name, symbol: 'none', lineStyle: { opacity: 0 }, areaStyle: { color: tokens.primary, opacity }, tooltip: { show: false } }]
    const o = baseOption(tokens)
    const tooltipSeries = [{ name: 'P05', type: 'line', data: p05, symbol: 'none', lineStyle: { opacity: 0 } }, { name: 'P10', type: 'line', data: p10, symbol: 'none', lineStyle: { opacity: 0 } }, { name: 'P25', type: 'line', data: p25, symbol: 'none', lineStyle: { opacity: 0 } }, { name: 'P50 median', type: 'line', data: p50, symbol: 'none', lineStyle: { color: mode === 'dark' ? '#ffffff' : '#0f172a', width: 3 } }, { name: 'P75', type: 'line', data: p75, symbol: 'none', lineStyle: { opacity: 0 } }, { name: 'P90', type: 'line', data: p90, symbol: 'none', lineStyle: { opacity: 0 } }, { name: 'P95', type: 'line', data: p95, symbol: 'none', lineStyle: { opacity: 0 } }]
    return { ...o, title: { text: `Path #${pathIndex} · Current percentile ${currentPercentile}% · Terminal percentile ${terminalPercentile}%`, subtext: 'Population Envelope vs Selected Path', left: 46, top: 2, textStyle: { color: tokens.text, fontSize: 10, fontWeight: 600 }, subtextStyle: { color: tokens.muted, fontSize: 9 } }, legend: { top: 28, left: 46, itemWidth: 18, itemHeight: 8, textStyle: { color: tokens.muted, fontSize: 9 }, data: ['P05–P95 band', 'P10–P90 band', 'P25–P75 band', 'P50 median', 'Selected path', 'KO barrier', 'Coupon barriers', 'KI barrier'] }, xAxis: { ...o.xAxis, data: dates, axisLabel: { ...o.xAxis.axisLabel, interval: 5, formatter: (v: string) => v.slice(2, 7) } }, yAxis: { ...o.yAxis, name: 'Worst Of %', min: 40, max: 115 }, series: [...band('P05–P95 band', p05!, p95!, mode === 'dark' ? .10 : .06), ...band('P10–P90 band', p10!, p90!, mode === 'dark' ? .20 : .12), ...band('P25–P75 band', p25!, p75!, mode === 'dark' ? .35 : .22), ...tooltipSeries, { name: 'Selected path', type: 'line', data: selectedSeries, lineStyle: { color: mode === 'dark' ? '#60a5fa' : '#2563eb', width: 4 }, symbol: 'none', z: 20 }, { name: 'KO barrier', type: 'line', data: dates.map(() => economics.knockOutBarrier * 100), lineStyle: { color: tokens.success, type: 'dashed', width: 1.5 }, symbol: 'none', z: 15 }, { name: 'Coupon barriers', type: 'line', data: dates.map(() => economics.couponUpperBarrier * 100), lineStyle: { color: tokens.warning, type: 'dashed', width: 1 }, symbol: 'none', z: 15 }, { name: 'Coupon barriers', type: 'line', data: dates.map(() => economics.couponLowerBarrier * 100), lineStyle: { color: tokens.warning, type: 'dashed', width: 1 }, symbol: 'none', z: 15 }, { name: 'KI barrier', type: 'line', data: dates.map(() => economics.knockInBarrier * 100), lineStyle: { color: tokens.danger, type: 'dashed', width: 1.5 }, symbol: 'none', z: 15 }], tooltip: { ...o.tooltip, formatter: (params: Array<{ seriesName: string; data: number; axisValue: string }>) => { const visible = params.filter((p) => ['P05', 'P10', 'P25', 'P50 median', 'P75', 'P90', 'P95', 'Selected path'].includes(p.seriesName)); return [`${params[0]?.axisValue ?? ''}`, ...visible.map((p) => `${p.seriesName}: ${Number(p.data).toFixed(1)}%`)].join('<br/>') } } }
  }, [mode, path, currentPercentile, terminalPercentile, tokens, economics, dates, paths, pathIndex, selectedSeries])
  if (!bundle || !path) return <PanelLoading title="Quantile Fan" subtitle="Population Envelope vs Selected Path" />
  return <ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge />
})

export const StateOccupancyTile = memo(function StateOccupancyTile() { const { tokens } = useTheme(); const bundle = useSimulationStore((s) => s.bundle); const option = useMemo(() => { const paths = bundle?.paths ?? []; const dates = paths[0]?.dates ?? []; const series = ['Alive', 'Coupon Accruing', 'Knocked Out', 'Knocked In'].map((name, state) => ({ name, type: 'line', stack: 'share', areaStyle: { opacity: .75 }, symbol: 'none', lineStyle: { width: 0 }, itemStyle: { color: [tokens.primary, tokens.warning, tokens.success, tokens.danger][state] }, data: dates.map((_, i) => { const active = paths.filter((p) => { const o = p.observations[i]!; return state === 2 ? o.knockOutAtDate : state === 3 ? o.knockInAtDate : state === 1 ? o.couponAccrued > 0 && !o.knockOutAtDate : !o.knockOutAtDate && !o.knockInAtDate && o.couponAccrued === 0 }).length; return +(active / paths.length * 100).toFixed(1) }) })); const o = baseOption(tokens); return { ...o, xAxis: { ...o.xAxis, data: dates, axisLabel: { ...o.xAxis.axisLabel, interval: 5, formatter: (v: string) => v.slice(2, 7) } }, yAxis: { ...o.yAxis, max: 100, name: 'Share %' }, legend: { top: 0, textStyle: { color: tokens.muted, fontSize: 9 } }, series } }, [tokens, bundle]); if (!bundle) return <PanelLoading title="State Occupancy" subtitle="Share of population by state" />; return <ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /> })

export const BarrierHeatmapTile = memo(function BarrierHeatmapTile() { const { tokens } = useTheme(); const bundle = useSimulationStore((s) => s.bundle); const option = useMemo(() => { const paths = bundle?.paths ?? []; const dates = paths[0]?.dates ?? []; const rows = ['KI crossing', 'KO crossing', 'Coupon eligible']; const data = rows.flatMap((_, r) => dates.map((_, i) => [i, r, +(paths.filter((p) => r === 0 ? p.observations[i]!.knockInAtDate : r === 1 ? p.observations[i]!.knockOutAtDate : p.observations[i]!.couponAccrued > 0).length / paths.length * 100).toFixed(1)])); return { ...baseOption(tokens), xAxis: { type: 'category', data: dates, axisLabel: { color: tokens.muted, fontSize: 9, interval: 5, formatter: (v: string) => v.slice(2, 7) } }, yAxis: { type: 'category', data: rows, axisLabel: { color: tokens.muted, fontSize: 9 } }, visualMap: { min: 0, max: 100, calculable: false, orient: 'horizontal', left: 'center', top: 0, textStyle: { color: tokens.muted, fontSize: 9 }, inRange: { color: [tokens.grid, tokens.primary, tokens.danger] } }, series: [{ type: 'heatmap', data, label: { show: false } }] } }, [tokens, bundle]); if (!bundle) return <PanelLoading title="Barrier Heatmap" subtitle="KI / KO / coupon crossing share" />; return <ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /> })

export const PathDistributionPositionTile = memo(function PathDistributionPositionTile() { const path = useSelectedPath(); const { tokens } = useTheme(); const bundle = useSimulationStore((s) => s.bundle); const values = bundle?.distributions.totalPayoff.values ?? []; const pathIndex = path?.pathIndex ?? 0; const value = path?.payoff ?? 0; const rank = path ? percentile(value, values) : 0; const option = useMemo(() => ({ ...baseOption(tokens), grid: { left: 20, right: 20, top: 36, bottom: 24 }, xAxis: { type: 'value', min: Math.min(...values), max: Math.max(...values), axisLabel: { color: tokens.muted, fontSize: 9 } }, yAxis: { show: false, type: 'value', max: 1 }, series: [{ type: 'line', data: values.map((v) => [v, .5]), symbol: 'none', lineStyle: { color: tokens.primary, opacity: .18, width: 8 }, markLine: { symbol: 'none', label: { formatter: `Path #${pathIndex} · ${rank}th percentile`, color: tokens.success }, lineStyle: { color: tokens.success, width: 2 }, data: [{ xAxis: value }] } }] }), [tokens, value, rank, pathIndex, values]); if (!bundle || !path) return <PanelLoading title="Path Distribution Position" subtitle="Selected path vs population" />; return <div className="flex h-full flex-col justify-center px-4"><div className="mb-2 flex items-end justify-between"><div><p className="eyebrow">Selected path</p><p className="text-3xl font-semibold text-main">#{pathIndex}</p></div><div className="text-right"><p className="text-2xl font-semibold text-success">{rank}th</p><p className="text-[10px] text-muted">population percentile</p></div></div><div className="h-24"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></div></div> })