import ReactECharts from 'echarts-for-react'
import { memo, useMemo } from 'react'
import { deriveTradeAnalytics, DEFAULT_TRADE_ECONOMICS, useTradeEconomicsStore } from '../../../store/tradeEconomicsStore'
import { useTheme } from '../../themes/ThemeProvider'
import { PanelCard } from '../../shared/components/PanelCard'
import { StatsBadge } from '../../shared/components/StatsBadge'

const pct = (v: number) => `${(v * 100).toFixed(0)}%`
export const TradeSummaryTile = memo(function TradeSummaryTile() { const s = useTradeEconomicsStore(); return <PanelCard title="Trade Summary" subtitle="Current product economics" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3 sm:grid-cols-4"><StatsBadge label="Strike" value={pct(s.strike)} /><StatsBadge label="KI" value={pct(s.knockInBarrier)} tone="warning" /><StatsBadge label="KO" value={pct(s.knockOutBarrier)} tone="success" /><StatsBadge label="Coupon" value={pct(s.couponRate)} tone="primary" /><StatsBadge label="Memory" value={s.memoryCouponEnabled ? 'Enabled' : 'Off'} /><StatsBadge label="Settlement" value={s.physicalSettlementEnabled ? 'Physical' : 'Cash'} /><StatsBadge label="Notional" value={s.notional} /><StatsBadge label="Maturity" value={`${s.maturityYears}Y`} /></div></PanelCard> })

export const EconomicsImpactSummaryTile = memo(function EconomicsImpactSummaryTile() { const s = useTradeEconomicsStore(); const a = deriveTradeAnalytics(s); const base = deriveTradeAnalytics(DEFAULT_TRADE_ECONOMICS); const delta = (v: number, b: number) => `${v - b >= 0 ? '+' : ''}${(v - b).toFixed(2)}`; return <PanelCard title="Economics Impact Summary" subtitle="Reactive expected-value consequences" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3"><StatsBadge label="Expected PV" value={`${a.expectedPv} (${delta(a.expectedPv, base.expectedPv)})`} tone={a.expectedPv >= base.expectedPv ? 'success' : 'warning'} /><StatsBadge label="Coupon PV" value={`${a.couponPv} (${delta(a.couponPv, base.couponPv)})`} tone="primary" /><StatsBadge label="Put PV" value={`${a.putPv} (${delta(a.putPv, base.putPv)})`} tone="warning" /><StatsBadge label="KO Probability" value={`${a.koProbability}% (${delta(a.koProbability, base.koProbability)})`} tone="success" /><StatsBadge label="KI Probability" value={`${a.kiProbability}% (${delta(a.kiProbability, base.kiProbability)})`} tone="warning" /><StatsBadge label="Redemption" value={a.redemption} /></div></PanelCard> })

export const SensitivityTornadoTile = memo(function SensitivityTornadoTile() { const { tokens } = useTheme(); const s = useTradeEconomicsStore(); const impact = [{ name: 'Coupon Rate', value: Math.abs(deriveTradeAnalytics({ ...s, couponRate: s.couponRate + .01 }).expectedPv - deriveTradeAnalytics(s).expectedPv) }, { name: 'KI Barrier', value: Math.abs(deriveTradeAnalytics({ ...s, knockInBarrier: s.knockInBarrier + .01 }).expectedPv - deriveTradeAnalytics(s).expectedPv) }, { name: 'KO Barrier', value: Math.abs(deriveTradeAnalytics({ ...s, knockOutBarrier: s.knockOutBarrier + .01 }).expectedPv - deriveTradeAnalytics(s).expectedPv) }, { name: 'Strike', value: Math.abs(deriveTradeAnalytics({ ...s, strike: s.strike + .01 }).expectedPv - deriveTradeAnalytics(s).expectedPv) }, { name: 'Coupon Upper', value: Math.abs(deriveTradeAnalytics({ ...s, couponUpperBarrier: s.couponUpperBarrier + .01 }).expectedPv - deriveTradeAnalytics(s).expectedPv) }, { name: 'Coupon Lower', value: Math.abs(deriveTradeAnalytics({ ...s, couponLowerBarrier: s.couponLowerBarrier + .01 }).expectedPv - deriveTradeAnalytics(s).expectedPv) }].sort((a, b) => b.value - a.value); const option = useMemo(() => ({ grid: { left: 92, right: 30, top: 18, bottom: 28 }, xAxis: { type: 'value', axisLabel: { color: tokens.muted, fontSize: 9 }, splitLine: { lineStyle: { color: tokens.grid } } }, yAxis: { type: 'category', data: impact.map((d) => d.name), axisLabel: { color: tokens.muted, fontSize: 9 } }, series: [{ type: 'bar', data: impact.map((d) => d.value), itemStyle: { color: tokens.primary }, label: { show: true, position: 'right', color: tokens.text, fontSize: 9, formatter: ({ value }: { value: number }) => `+${value.toFixed(2)}` } }] }), [impact, tokens]); return <PanelCard title="Sensitivity Tornado" subtitle="One-step PV impact ranking" className="h-full"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })

export const ParameterImpactMatrixTile = memo(function ParameterImpactMatrixTile() { const { tokens } = useTheme(); const s = useTradeEconomicsStore(); const base = deriveTradeAnalytics(s); const params = [{ name: 'Strike', patch: { strike: s.strike + .01 } }, { name: 'KI Barrier', patch: { knockInBarrier: s.knockInBarrier + .01 } }, { name: 'KO Barrier', patch: { knockOutBarrier: s.knockOutBarrier + .01 } }, { name: 'Coupon Rate', patch: { couponRate: s.couponRate + .01 } }, { name: 'Coupon Lower', patch: { couponLowerBarrier: s.couponLowerBarrier + .01 } }, { name: 'Coupon Upper', patch: { couponUpperBarrier: s.couponUpperBarrier + .01 } }]; const cols = ['PV', 'KI Probability', 'KO Probability', 'Coupon PV', 'Put PV']; const matrix = params.flatMap((p, r) => { const next = deriveTradeAnalytics({ ...s, ...p.patch }); const values = [next.expectedPv - base.expectedPv, next.kiProbability - base.kiProbability, next.koProbability - base.koProbability, next.couponPv - base.couponPv, next.putPv - base.putPv]; return values.map((value, c) => [c, r, +value.toFixed(2)]) }); const option = { grid: { left: 92, right: 20, top: 34, bottom: 28 }, xAxis: { type: 'category', data: cols, axisLabel: { color: tokens.muted, fontSize: 9 } }, yAxis: { type: 'category', data: params.map((p) => p.name), axisLabel: { color: tokens.muted, fontSize: 9 } }, visualMap: { min: -2, max: 2, calculable: false, orient: 'horizontal', left: 'center', top: 0, textStyle: { color: tokens.muted, fontSize: 9 }, inRange: { color: [tokens.danger, tokens.panel, tokens.success] } }, series: [{ type: 'heatmap', data: matrix, label: { show: true, color: tokens.text, fontSize: 8 } }] }; return <PanelCard title="Parameter Impact Matrix" subtitle="Directional sensitivity across key analytics" className="h-full"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })
