import ReactECharts from 'echarts-for-react'
import { memo, useMemo } from 'react'
import { DEFAULT_TRADE_ECONOMICS, useTradeEconomicsStore } from '../../../store/tradeEconomicsStore'
import { useTradeAnalytics } from '../../../hooks'
import { useTheme } from '../../themes/ThemeProvider'
import { PanelCard } from '../../shared/components/PanelCard'
import { PanelLoading } from '../../shared/components/AsyncPanel'
import { StatsBadge } from '../../shared/components/StatsBadge'

const pct = (v: number) => `${(v * 100).toFixed(0)}%`
export const TradeSummaryTile = memo(function TradeSummaryTile() { const s = useTradeEconomicsStore(); return <PanelCard title="Trade Summary" subtitle="Current product economics" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3 sm:grid-cols-4"><StatsBadge label="Strike" value={pct(s.strike)} /><StatsBadge label="KI" value={pct(s.knockInBarrier)} tone="warning" /><StatsBadge label="KO" value={pct(s.knockOutBarrier)} tone="success" /><StatsBadge label="Coupon" value={pct(s.couponRate)} tone="primary" /><StatsBadge label="Memory" value={s.memoryCouponEnabled ? 'Enabled' : 'Off'} /><StatsBadge label="Settlement" value={s.physicalSettlementEnabled ? 'Physical' : 'Cash'} /><StatsBadge label="Notional" value={s.notional} /><StatsBadge label="Maturity" value={`${s.maturityYears}Y`} /></div></PanelCard> })

export const EconomicsImpactSummaryTile = memo(function EconomicsImpactSummaryTile() { const s = useTradeEconomicsStore(); const current = useTradeAnalytics(s); const baseline = useTradeAnalytics(DEFAULT_TRADE_ECONOMICS); if (!current.data || !baseline.data) return <PanelLoading title="Economics Impact Summary" subtitle="Reactive expected-value consequences" />; const a = current.data; const base = baseline.data; const delta = (v: number, b: number) => `${v - b >= 0 ? '+' : ''}${(v - b).toFixed(2)}`; return <PanelCard title="Economics Impact Summary" subtitle="Reactive expected-value consequences" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3"><StatsBadge label="Expected PV" value={`${a.expectedPv} (${delta(a.expectedPv, base.expectedPv)})`} tone={a.expectedPv >= base.expectedPv ? 'success' : 'warning'} /><StatsBadge label="Coupon PV" value={`${a.couponPv} (${delta(a.couponPv, base.couponPv)})`} tone="primary" /><StatsBadge label="Put PV" value={`${a.putPv} (${delta(a.putPv, base.putPv)})`} tone="warning" /><StatsBadge label="KO Probability" value={`${a.koProbability}% (${delta(a.koProbability, base.koProbability)})`} tone="success" /><StatsBadge label="KI Probability" value={`${a.kiProbability}% (${delta(a.kiProbability, base.kiProbability)})`} tone="warning" /><StatsBadge label="Redemption" value={a.redemption} /></div></PanelCard> })

export const SensitivityTornadoTile = memo(function SensitivityTornadoTile() { const { tokens } = useTheme(); const s = useTradeEconomicsStore(); const base = useTradeAnalytics(s); const couponRateUp = useTradeAnalytics({ ...s, couponRate: s.couponRate + .01 }); const kiUp = useTradeAnalytics({ ...s, knockInBarrier: s.knockInBarrier + .01 }); const koUp = useTradeAnalytics({ ...s, knockOutBarrier: s.knockOutBarrier + .01 }); const strikeUp = useTradeAnalytics({ ...s, strike: s.strike + .01 }); const couponUpperUp = useTradeAnalytics({ ...s, couponUpperBarrier: s.couponUpperBarrier + .01 }); const couponLowerUp = useTradeAnalytics({ ...s, couponLowerBarrier: s.couponLowerBarrier + .01 }); const impact = [{ name: 'Coupon Rate', value: Math.abs((couponRateUp.data?.expectedPv ?? 0) - (base.data?.expectedPv ?? 0)) }, { name: 'KI Barrier', value: Math.abs((kiUp.data?.expectedPv ?? 0) - (base.data?.expectedPv ?? 0)) }, { name: 'KO Barrier', value: Math.abs((koUp.data?.expectedPv ?? 0) - (base.data?.expectedPv ?? 0)) }, { name: 'Strike', value: Math.abs((strikeUp.data?.expectedPv ?? 0) - (base.data?.expectedPv ?? 0)) }, { name: 'Coupon Upper', value: Math.abs((couponUpperUp.data?.expectedPv ?? 0) - (base.data?.expectedPv ?? 0)) }, { name: 'Coupon Lower', value: Math.abs((couponLowerUp.data?.expectedPv ?? 0) - (base.data?.expectedPv ?? 0)) }].sort((a, b) => b.value - a.value); const option = useMemo(() => ({ grid: { left: 92, right: 30, top: 18, bottom: 28 }, xAxis: { type: 'value', axisLabel: { color: tokens.muted, fontSize: 9 }, splitLine: { lineStyle: { color: tokens.grid } } }, yAxis: { type: 'category', data: impact.map((d) => d.name), axisLabel: { color: tokens.muted, fontSize: 9 } }, series: [{ type: 'bar', data: impact.map((d) => d.value), itemStyle: { color: tokens.primary }, label: { show: true, position: 'right', color: tokens.text, fontSize: 9, formatter: ({ value }: { value: number }) => `+${value.toFixed(2)}` } }] }), [impact, tokens]); if (!base.data || !couponRateUp.data || !kiUp.data || !koUp.data || !strikeUp.data || !couponUpperUp.data || !couponLowerUp.data) return <PanelLoading title="Sensitivity Tornado" subtitle="One-step PV impact ranking" />; return <PanelCard title="Sensitivity Tornado" subtitle="One-step PV impact ranking" className="h-full"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })

export const ParameterImpactMatrixTile = memo(function ParameterImpactMatrixTile() { const { tokens } = useTheme(); const s = useTradeEconomicsStore(); const base = useTradeAnalytics(s); const strikeUp = useTradeAnalytics({ ...s, strike: s.strike + .01 }); const kiUp = useTradeAnalytics({ ...s, knockInBarrier: s.knockInBarrier + .01 }); const koUp = useTradeAnalytics({ ...s, knockOutBarrier: s.knockOutBarrier + .01 }); const couponRateUp = useTradeAnalytics({ ...s, couponRate: s.couponRate + .01 }); const couponLowerUp = useTradeAnalytics({ ...s, couponLowerBarrier: s.couponLowerBarrier + .01 }); const couponUpperUp = useTradeAnalytics({ ...s, couponUpperBarrier: s.couponUpperBarrier + .01 }); if (!base.data || !strikeUp.data || !kiUp.data || !koUp.data || !couponRateUp.data || !couponLowerUp.data || !couponUpperUp.data) return <PanelLoading title="Parameter Impact Matrix" subtitle="Directional sensitivity across key analytics" />; const b = base.data; const params = [{ name: 'Strike', next: strikeUp.data }, { name: 'KI Barrier', next: kiUp.data }, { name: 'KO Barrier', next: koUp.data }, { name: 'Coupon Rate', next: couponRateUp.data }, { name: 'Coupon Lower', next: couponLowerUp.data }, { name: 'Coupon Upper', next: couponUpperUp.data }]; const cols = ['PV', 'KI Probability', 'KO Probability', 'Coupon PV', 'Put PV']; const matrix = params.flatMap((p, r) => { const values = [p.next.expectedPv - b.expectedPv, p.next.kiProbability - b.kiProbability, p.next.koProbability - b.koProbability, p.next.couponPv - b.couponPv, p.next.putPv - b.putPv]; return values.map((value, c) => [c, r, +value.toFixed(2)]) }); const option = { grid: { left: 92, right: 20, top: 34, bottom: 28 }, xAxis: { type: 'category', data: cols, axisLabel: { color: tokens.muted, fontSize: 9 } }, yAxis: { type: 'category', data: params.map((p) => p.name), axisLabel: { color: tokens.muted, fontSize: 9 } }, visualMap: { min: -2, max: 2, calculable: false, orient: 'horizontal', left: 'center', top: 0, textStyle: { color: tokens.muted, fontSize: 9 }, inRange: { color: [tokens.danger, tokens.panel, tokens.success] } }, series: [{ type: 'heatmap', data: matrix, label: { show: true, color: tokens.text, fontSize: 8 } }] }; return <PanelCard title="Parameter Impact Matrix" subtitle="Directional sensitivity across key analytics" className="h-full"><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })