import ReactECharts from 'echarts-for-react'
import { memo } from 'react'
import { useTheme } from '../../themes/ThemeProvider'
import { useValuationExplain } from '../../../hooks'
import { useValuationExplainStore } from '../../../store/valuationExplainStore'
import { PanelCard } from '../../shared/components/PanelCard'
import { PanelLoading } from '../../shared/components/AsyncPanel'
import { StatsBadge } from '../../shared/components/StatsBadge'
export const ValuationExplainSummaryTile = memo(function ValuationExplainSummaryTile() { const { data } = useValuationExplain(); if (!data) return <PanelLoading title="Valuation Explain Summary" subtitle="Market-move P&L versus valuation methodology P&L" />; const state = data.state; return <PanelCard title="Valuation Explain Summary" subtitle="Market-move P&L versus valuation methodology P&L" className="h-full"><div className="grid h-full grid-cols-2 gap-2 p-3 sm:grid-cols-3"><StatsBadge label="Previous PV" value={state.previousPV.toFixed(2)} /><StatsBadge label="Current PV" value={state.currentPV.toFixed(2)} tone="primary" /><StatsBadge label="Market Explain" value={state.marketExplainedPnL.toFixed(2)} tone="primary" /><StatsBadge label="PLVA" value={state.plvaPnL.toFixed(2)} tone="warning" /><StatsBadge label="Residual" value={state.residualPnL.toFixed(2)} tone="danger" /><StatsBadge label="Total Change" value={state.totalPnL.toFixed(2)} tone="success" /></div></PanelCard> })
export const MasterExplainWaterfallTile = memo(function MasterExplainWaterfallTile() { const { tokens } = useTheme(); const { data } = useValuationExplain(); if (!data) return <PanelLoading title="Master Explain Waterfall" subtitle="Previous PV → market explain → PLVA → residual → current PV" />; const state = data.state; const labels = ['Previous PV', 'Market Explain', 'PLVA', 'Residual', 'Current PV']; const vals = [state.previousPV, state.marketExplainedPnL, state.plvaPnL, state.residualPnL, state.currentPV]; return <PanelCard title="Master Explain Waterfall" subtitle="Previous PV → market explain → PLVA → residual → current PV" className="h-full"><ReactECharts option={{ xAxis: { type: 'category', data: labels, axisLabel: { color: tokens.muted, fontSize: 9, rotate: 20 } }, yAxis: { type: 'value', axisLabel: { color: tokens.muted, fontSize: 9 }, splitLine: { lineStyle: { color: tokens.grid } } }, series: [{ type: 'bar', data: vals.map((v, i) => ({ value: v, itemStyle: { color: i === 1 ? tokens.primary : i === 2 ? '#a855f7' : i === 3 ? tokens.danger : tokens.muted } })) }] }} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })
export const TaylorExplainTile = memo(function TaylorExplainTile() { const { tokens } = useTheme(); const { data } = useValuationExplain(); if (!data) return <PanelLoading title="Taylor Explain" subtitle="Market-risk attribution only — not valuation methodology" />; const taylor = data.taylor; const names = ['Delta', 'Gamma', 'Vega', 'Theta', 'FX', 'Rates', 'Corr', 'Dividend', 'Residual']; const values = [taylor.delta, taylor.gamma, taylor.vega, taylor.theta, taylor.fx, taylor.rates, taylor.correlation, taylor.dividend, taylor.residual]; return <PanelCard title="Taylor Explain" subtitle="Market-risk attribution only — not valuation methodology" className="h-full"><ReactECharts option={{ xAxis: { type: 'category', data: names, axisLabel: { color: tokens.muted, fontSize: 9, rotate: 25 } }, yAxis: { type: 'value', axisLabel: { color: tokens.muted, fontSize: 9 }, splitLine: { lineStyle: { color: tokens.grid } } }, series: [{ type: 'bar', data: values.map((v) => ({ value: v, itemStyle: { color: v >= 0 ? tokens.primary : tokens.danger } })) }] }} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })
export const PLVATile = memo(function PLVATile() { const { tokens } = useTheme(); const { data } = useValuationExplain(); const select = useValuationExplainStore((s) => s.selectCategory); if (!data) return <PanelLoading title="PLVA Explain" subtitle="Valuation methodology adjustments — not Greeks" />; const plva = data.plva; return <PanelCard title="PLVA Explain" subtitle="Valuation methodology adjustments — not Greeks" className="h-full"><ReactECharts option={{ xAxis: { type: 'category', data: plva.map((x) => x.category), axisLabel: { color: tokens.muted, fontSize: 9, rotate: 28 } }, yAxis: { type: 'value', axisLabel: { color: tokens.muted, fontSize: 9 }, splitLine: { lineStyle: { color: tokens.grid } } }, series: [{ type: 'bar', data: plva.map((x) => ({ value: x.contribution, itemStyle: { color: '#a855f7' } })) }] }} style={{ height: '100%', width: '100%' }} notMerge onEvents={{ click: (p: { dataIndex?: number }) => typeof p.dataIndex === 'number' && select(plva[p.dataIndex]!.category) }} /></PanelCard> })
