import { create } from 'zustand'
import { useSelectedPath } from './explorerStore'
import { useTradeEconomicsStore, type TradeEconomics } from './tradeEconomicsStore'
export type CashflowType = 'coupon' | 'redemption' | 'cash_settlement' | 'physical_delivery' | 'funding'
export type Cashflow = { id: string; date: string; type: CashflowType; amount: number; currency: string; probability: number; discountFactor: number; presentValue: number; realized: boolean }
export type CashflowState = { selectedCashflowId: string | null; selectCashflow: (id: string) => void }
export const useCashflowStore = create<CashflowState>((set) => ({ selectedCashflowId: null, selectCashflow: (selectedCashflowId) => set({ selectedCashflowId }) }))
export function buildCashflows(path: ReturnType<typeof useSelectedPath>, trade: TradeEconomics) { return path.dates.map((date, i): Cashflow => { const final = i === path.dates.length - 1; const amount = final ? trade.notional : +(trade.notional * trade.couponRate / 12 * (path.observations[i]!.couponAccrued > 0 ? 1 : 0)).toFixed(2); const df = +(1 / (1 + .04) ** ((i + 1) / 12)).toFixed(4); return { id: `cf-${i}`, date, type: final ? (trade.physicalSettlementEnabled ? 'physical_delivery' : 'redemption') : 'coupon', amount, currency: 'USD', probability: final ? .98 : .85, discountFactor: df, presentValue: +(amount * df).toFixed(2), realized: i < 2 } }) }
export function useCashflowAnalytics() { const path = useSelectedPath(); const trade = useTradeEconomicsStore(); const cashflows = buildCashflows(path, trade); const grossCashflow = cashflows.reduce((s: number, c: Cashflow) => s + c.amount, 0); const presentValue = cashflows.reduce((s: number, c: Cashflow) => s + c.presentValue, 0); const realized = cashflows.filter((c: Cashflow) => c.realized).reduce((s, c) => s + c.amount, 0); const carry = realized * .02 + trade.couponRate * trade.notional; const mtm = presentValue - trade.notional; return { cashflows, grossCashflow, presentValue, realized, future: grossCashflow - realized, realizedPnL: realized - trade.notional * .02, unrealizedPnL: mtm, mtmPnL: mtm, carryPnL: carry, totalPnL: mtm + carry, path } }
