import { create } from 'zustand'
export type OHLCBar = { date: string; open: number; high: number; low: number; close: number; volume: number }
export type Underlying = { symbol: string; spot: number; baselineSpot: number; dividendYield: number; currency: string; historicalPrices: OHLCBar[] }
export type FXPair = { pair: string; spot: number; baselineSpot: number; volatility: number }
export type MarketDataState = { underlyings: Underlying[]; fxPairs: FXPair[]; correlations: number[][]; vol: { atmVol: number; skew: number; curvature: number; termSlope: number }; selectedUnderlying: string; selectedFX: string; updateSpot: (symbol: string, spot: number) => void; updateFX: (pair: string, spot: number) => void; updateVol: (patch: Partial<MarketDataState['vol']>) => void; updateCorrelation: (row: number, col: number, value: number) => void; selectUnderlying: (symbol: string) => void; applyShock: (type: 'spotUp' | 'spotDown' | 'volUp' | 'volDown' | 'corrUp' | 'corrDown' | 'fxUp' | 'fxDown') => void }
const makeBars = (start: number, seed: number): OHLCBar[] => Array.from({ length: 36 }, (_, i) => { const close = +(start * (1 + Math.sin(i / 4 + seed) * .08 + i * .002)).toFixed(2); return { date: `2023-${String((i % 12) + 1).padStart(2, '0')}-01`, open: +(close * .99).toFixed(2), high: +(close * 1.02).toFixed(2), low: +(close * .97).toFixed(2), close, volume: 800000 + i * 15000 } })
const initialUnderlyings: Underlying[] = [{ symbol: 'AAPL', spot: 185, baselineSpot: 185, dividendYield: .005, currency: 'USD', historicalPrices: makeBars(185, 1) }, { symbol: 'MSFT', spot: 420, baselineSpot: 420, dividendYield: .007, currency: 'USD', historicalPrices: makeBars(420, 2) }, { symbol: 'NVDA', spot: 122, baselineSpot: 122, dividendYield: .001, currency: 'USD', historicalPrices: makeBars(122, 3) }]
const initialFX: FXPair[] = [{ pair: 'USDSGD', spot: 1.34, baselineSpot: 1.34, volatility: .07 }, { pair: 'EURUSD', spot: 1.08, baselineSpot: 1.08, volatility: .09 }, { pair: 'USDJPY', spot: 151.2, baselineSpot: 151.2, volatility: .11 }]
function load(): Partial<MarketDataState> { try { return JSON.parse(localStorage.getItem('fina-market-data') ?? '{}') as Partial<MarketDataState> } catch { return {} } }
const saved = typeof window !== 'undefined' ? load() : {}
function persist(state: MarketDataState) { try { localStorage.setItem('fina-market-data', JSON.stringify({ underlyings: state.underlyings, fxPairs: state.fxPairs, correlations: state.correlations, vol: state.vol, selectedUnderlying: state.selectedUnderlying, selectedFX: state.selectedFX })) } catch { /* optional */ } }
export const useMarketDataStore = create<MarketDataState>((set, get) => ({ underlyings: saved.underlyings ?? initialUnderlyings, fxPairs: saved.fxPairs ?? initialFX, correlations: saved.correlations ?? [[1, .55, .48], [.55, 1, .62], [.48, .62, 1]], vol: saved.vol ?? { atmVol: .24, skew: -.18, curvature: .12, termSlope: .015 }, selectedUnderlying: saved.selectedUnderlying ?? 'AAPL', selectedFX: saved.selectedFX ?? 'USDSGD', updateSpot: (symbol, spot) => { const underlyings = get().underlyings.map((u) => u.symbol === symbol ? { ...u, spot: Math.max(.01, spot) } : u); set({ underlyings }); persist({ ...get(), underlyings }) }, updateFX: (pair, spot) => { const fxPairs = get().fxPairs.map((f) => f.pair === pair ? { ...f, spot: Math.max(.0001, spot) } : f); set({ fxPairs }); persist({ ...get(), fxPairs }) }, updateVol: (patch) => { const vol = { ...get().vol, ...patch }; set({ vol }); persist({ ...get(), vol }) }, updateCorrelation: (row, col, value) => { const correlations = get().correlations.map((r) => [...r]); const v = Math.max(-1, Math.min(1, value)); correlations[row]![col] = v; correlations[col]![row] = v; set({ correlations }); persist({ ...get(), correlations }) }, selectUnderlying: (selectedUnderlying) => set({ selectedUnderlying }), applyShock: (type) => { const s = get(); if (type.startsWith('spot')) s.updateSpot(s.selectedUnderlying, (s.underlyings.find((u) => u.symbol === s.selectedUnderlying)?.spot ?? 1) * (type === 'spotUp' ? 1.05 : .95)); else if (type.startsWith('fx')) s.updateFX(s.selectedFX, (s.fxPairs.find((f) => f.pair === s.selectedFX)?.spot ?? 1) * (type === 'fxUp' ? 1.02 : .98)); else if (type.startsWith('vol')) s.updateVol({ atmVol: s.vol.atmVol + (type === 'volUp' ? .01 : -.01) }); else { const correlations = s.correlations.map((r) => [...r]); const amount = type === 'corrUp' ? .1 : -.1; for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) if (i !== j) correlations[i]![j] = Math.max(-1, Math.min(1, correlations[i]![j]! + amount)); set({ correlations }); persist({ ...get(), correlations }) } } }))
