import clsx from 'clsx'
import { Handle, Position, type NodeProps } from '@xyflow/react'
import { memo } from 'react'
import { useTheme } from '../../themes/ThemeProvider'
import type { NodeState, PayoffNodeId } from '../../shared/types'
export interface PayoffNodeData { label: string; nodeId: PayoffNodeId; state: NodeState; isLossRelated: boolean; isSelected: boolean; [key: string]: unknown }
export const PayoffGraphNode = memo(function PayoffGraphNode({ data }: NodeProps & { data: PayoffNodeData }) {
  const { tokens, mode } = useTheme()
  const glow = data.state === 'active' ? data.isLossRelated ? 'animate-[node-glow-danger_2s_ease-in-out_infinite]' : 'animate-[node-glow-active_2s_ease-in-out_infinite]' : data.state === 'visited' ? data.isLossRelated ? 'animate-[node-glow-danger_2.4s_ease-in-out_infinite]' : 'animate-[node-glow_2.4s_ease-in-out_infinite]' : ''
  const stateStyle = data.isLossRelated && (data.state === 'visited' || data.state === 'active') ? { borderColor: tokens.danger, backgroundColor: mode === 'dark' ? 'rgba(239,68,68,.15)' : 'rgba(220,38,38,.10)', color: mode === 'dark' ? '#fee2e2' : '#991b1b' } : data.state === 'active' ? { borderColor: tokens.success, backgroundColor: mode === 'dark' ? 'rgba(34,197,94,.15)' : 'rgba(22,163,74,.10)', color: tokens.text } : data.state === 'visited' ? { borderColor: tokens.primary, backgroundColor: mode === 'dark' ? 'rgba(59,130,246,.15)' : 'rgba(37,99,235,.10)', color: tokens.text } : data.state === 'skipped' ? { borderColor: tokens.border, backgroundColor: mode === 'dark' ? 'rgba(15,23,42,.5)' : 'rgba(226,232,240,.65)', color: tokens.muted, opacity: .45 } : { borderColor: tokens.border, backgroundColor: mode === 'dark' ? 'rgba(30,41,59,.6)' : 'rgba(241,245,249,.8)', color: tokens.muted, opacity: .7 }
  return <div className={clsx('min-w-[128px] rounded-md border px-3 py-2 shadow-md transition-all duration-300', data.isSelected && 'ring-2 ring-primary ring-offset-1 ring-offset-bg', glow)} style={stateStyle}><Handle type="target" position={Position.Left} className="!h-2 !w-2 !border-0" style={{ background: tokens.primary }} /><div className="text-[10px] font-semibold tracking-wide uppercase">{data.label}</div><div className="mt-0.5 font-mono text-[9px]" style={{ color: tokens.muted }}>{data.state}</div><Handle type="source" position={Position.Right} className="!h-2 !w-2 !border-0" style={{ background: tokens.primary }} /></div>
})
