import ReactECharts from 'echarts-for-react'
import { memo, useMemo } from 'react'
import { simulationBundle } from '../../../mock-data/generatePaths'
import { useSelectedPath } from '../../../store/explorerStore'
import { useTheme } from '../../themes/ThemeProvider'
import { PanelCard } from '../../shared/components/PanelCard'
import { StatsBadge } from '../../shared/components/StatsBadge'

type Metric = 'total' | 'coupon' | 'put' | 'worstOf'
const metricMeta: Record<Metric, { label: string; color: string }> = { total: { label: 'Total Payoff', color: '#3b82f6' }, coupon: { label: 'Coupon PV', color: '#f59e0b' }, put: { label: 'Put PV', color: '#ef4444' }, worstOf: { label: 'Worst-of Final', color: '#22c55e' } }
function valuesFor(metric: Metric) { const d = simulationBundle.distributions; return metric === 'total' ? d.totalPayoff.values : metric === 'coupon' ? d.couponPv.values : metric === 'put' ? d.putPv.values : d.worstOfFinal.values }
function histogram(values: number[], bins = 18) { const min = Math.min(...values); const max = Math.max(...values); const width = (max - min || 1) / bins; const counts = Array.from({ length: bins }, () => 0); for (const value of values) counts[Math.min(bins - 1, Math.max(0, Math.floor((value - min) / width)))]!++; return { centers: counts.map((_, i) => +(min + width * (i + .5)).toFixed(2)), counts } }

export const PayoffHistogramTile = memo(function PayoffHistogramTile() { const path = useSelectedPath(); const { tokens } = useTheme(); const stats = simulationBundle.distributions.totalPayoff; const marker = path.payoff; const option = useMemo(() => { const { centers, counts } = histogram(stats.values); const nearest = centers.reduce((best, value, i) => Math.abs(value - marker) < Math.abs(centers[best]! - marker) ? i : best, 0); return { backgroundColor: 'transparent', grid: { left: 44, right: 22, top: 38, bottom: 40 }, legend: { top: 4, textStyle: { color: tokens.muted, fontSize: 10 }, data: ['Population payoff', 'Selected path'] }, tooltip: { trigger: 'axis', backgroundColor: tokens.panel, borderColor: tokens.border, textStyle: { color: tokens.text, fontSize: 11 } }, xAxis: { type: 'category', data: centers.map(String), name: 'Total Payoff', nameTextStyle: { color: tokens.muted, fontSize: 10 }, axisLabel: { color: tokens.muted, fontSize: 9, rotate: 30 }, axisLine: { lineStyle: { color: tokens.border } } }, yAxis: { type: 'value', name: 'Paths', nameTextStyle: { color: tokens.muted, fontSize: 10 }, axisLabel: { color: tokens.muted, fontSize: 9 }, splitLine: { lineStyle: { color: tokens.grid } } }, series: [{ name: 'Population payoff', type: 'bar', data: counts, barWidth: '72%', itemStyle: { color: tokens.primary, opacity: .72, borderRadius: [3, 3, 0, 0] } }, { name: 'Selected path', type: 'line', data: centers.map((_, i) => i === nearest ? counts[i] : null), connectNulls: false, symbol: 'pin', symbolSize: 14, lineStyle: { color: tokens.success, width: 2 }, itemStyle: { color: tokens.success }, label: { show: true, formatter: `Path #${path.pathIndex}`, color: tokens.success, fontSize: 10 }, markLine: { symbol: 'none', lineStyle: { color: tokens.success, width: 2 }, label: { formatter: `Selected ${marker.toFixed(2)}`, color: tokens.success, fontSize: 10 }, data: [{ xAxis: nearest }] } }] } }, [marker, path.pathIndex, stats.values, tokens]); return <PanelCard title="Payoff Histogram" subtitle="Total payoff population with selected path marker" className="h-full" actions={<StatsBadge label="Selected PV" value={marker.toFixed(2)} tone="success" />}><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })

export const DistributionExplorerTile = memo(function DistributionExplorerTile() { const { tokens } = useTheme(); const metrics: Metric[] = ['total', 'coupon', 'put', 'worstOf']; const option = useMemo(() => { const series = metrics.map((metric) => { const values = valuesFor(metric); const { centers, counts } = histogram(values); const max = Math.max(...counts) || 1; return { name: metricMeta[metric].label, type: 'line', smooth: false, symbol: 'none', data: centers.map((x, i) => [x, +(counts[i]! / max * 100).toFixed(1)]), lineStyle: { color: metricMeta[metric].color, width: 2 }, itemStyle: { color: metricMeta[metric].color }, areaStyle: { color: metricMeta[metric].color, opacity: .06 } } }); return { backgroundColor: 'transparent', grid: { left: 48, right: 22, top: 42, bottom: 42 }, legend: { top: 4, textStyle: { color: tokens.muted, fontSize: 9 }, data: metrics.map((metric) => metricMeta[metric].label) }, tooltip: { trigger: 'axis', backgroundColor: tokens.panel, borderColor: tokens.border, textStyle: { color: tokens.text, fontSize: 11 }, valueFormatter: (v: unknown) => `${v}% of metric peak` }, xAxis: { type: 'value', name: 'Metric value', nameTextStyle: { color: tokens.muted, fontSize: 10 }, axisLabel: { color: tokens.muted, fontSize: 9 }, axisLine: { lineStyle: { color: tokens.border } } }, yAxis: { type: 'value', max: 100, name: 'Relative density', nameTextStyle: { color: tokens.muted, fontSize: 10 }, axisLabel: { color: tokens.muted, fontSize: 9, formatter: '{value}%' }, splitLine: { lineStyle: { color: tokens.grid } } }, series } }, [tokens]); return <PanelCard title="Distribution Explorer" subtitle="Compare normalized payoff, coupon, put, and worst-of distributions" className="h-full" actions={<div className="flex gap-1">{metrics.map((metric) => <span key={metric} className="rounded px-1.5 py-0.5 text-[9px]" style={{ color: metricMeta[metric].color, background: `${metricMeta[metric].color}18` }}>{metricMeta[metric].label}</span>)}</div>}><ReactECharts option={option} style={{ height: '100%', width: '100%' }} notMerge /></PanelCard> })
